### ISSUE TITLE
'"font-family-roboto"' is not assignable

### ISSUE THREAD

**Issue by jkleiser** [jkleiser/apprun-classyui-spa#1]
The first time I run `npm start`, and maybe later, I get
```
ERROR in .../apprun-classyui-spa/src/navbar.tsx(52,5):
TS2345: Argument of type '"font-family-roboto"' is not assignable to parameter of type 'TClassnamesArg'.
```
When I ctrl-C and start again, I do not get that error message.
The problem will probably go away when Classy-UI is past Beta.

**Comment by christianalfoni** [comment]
When changing the `config` file you have to restart the workflow process. Is that what happened? Or do you still get this error randomly?

**Comment by jkleiser** [comment]
I just made a fresh clone, and the same happened: On the first `nam start` I got the ERROR, but the next time no error. I will now try to change the `config` and start again.

**Comment by jkleiser** [comment]
A minor change to `classy-ui.config.js` (changing line 7 from `'1': '1px',` to `'': '1px',`) did not give any error.
The I changed the content of the config into this:
```
module.exports = {
  variables: ({ colors }) => ({
    colors: {
      ...colors,
      navbkg: "green"
    },
    fontFamily: {
      roboto: "Roboto"
    }
  })
}
```
That gave me this error:
```
ERROR in ./src/navbar.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Volumes/P3/apprun-classyui-spa/src/navbar.tsx: CLASSY-UI: Could not find classname font-family-roboto
  50 |     "display-block",
  51 |     "color-gray-600",
> 52 |     "font-family-roboto",
     |     ^^^^^^^^^^^^^^^^^^^^
  53 |     "text-decoration-none",
  54 |     "padding-top-2",
  55 |     "padding-right-2",
    at File.buildCodeFrameError (/Volumes/P3/apprun-classyui-spa/node_modules/@babel/core/lib/transformation/file/file.js:267:12)
    at NodePath.buildCodeFrameError (/Volumes/P3/apprun-classyui-spa/node_modules/@babel/traverse/lib/path/index.js:144:21)
<and more>
```
Can you spot the problem here?

**Comment by jkleiser** [comment]
old problem, now solved
