### ISSUE TITLE
Not sure how to do classy-ui.config.js right

### ISSUE THREAD

**Issue by jkleiser** [jkleiser/apprun-classyui-spa#2]
The (dead) file bad-classy-ui.config.xxxjs just shows that I've had problems getting classy-ui.config.js to do what I wanted. It may be related to issue #1.
The part re. borderWidths in classy-ui.config.js should not be needed. The reason for it being there is because I haven't been able to get `border-bottom-width` working (in navbar.tsx), but it didn't help me.

**Comment by christianalfoni** [comment]
Okay, so you tried the default config of `borderWidths` and the `border-bottom-width` classname did not work?

**Comment by jkleiser** [comment]
Right, I have not been able to get a border-bottom in my navbar this far; I have tried both `border-bottom-width` and `border-bottom-width-2`.

**Comment by jkleiser** [comment]
I tried to insert `className={c("border-bottom-width", "border-bottom-color-gray-500")}` in the `<h1>Hello CodeSandbox</h1>` of your https://codesandbox.io/s/classy-ui-demo-cjkjj, but the `border-bottom-color-gray-500` was not accepted. Maybe this demo needs an update?

**Comment by jkleiser** [comment]
now works
